### ISSUE TITLE
[Enhancement]: Add tool to Woo Admin

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/wc-smooth-generator#130]
### Describe the solution you'd like

Add generators to WooCommerce >  Status > Tools. It might be handy to have these in the admin instead of needing to use CLI

**Comment by coreymckrill** [comment]
@helgatheviking there actually is a (very limited) UI for Smooth Generator, but instead of being in WooCommerce > Status > Tools, it's just under the main Tools menu. Right now you can only generate products and orders (and you get an Easter Egg when you do!), but there's an intention to eventually have parity between the UI and the CLI, outlined in https://github.com/woocommerce/wc-smooth-generator/issues/120

**Comment by coreymckrill** [comment]
But this brings up an interesting question: 🤔 would the Admin UI be more discoverable if it was somewhere under the WooCommerce menu item?

**Comment by helgatheviking** [comment]
I was looking at the readme for instructions so never even thought to check the UI.

Maybe instead, this issue should be for an update to the readme?

**Comment by coreymckrill** [comment]
PR to update the readme: https://github.com/woocommerce/wc-smooth-generator/pull/132
