### ISSUE TITLE
PHP notice when generating customers

### ISSUE THREAD

**Issue by warrendholmes** [woocommerce/wc-smooth-generator#18]
When generating new customers I see the following notice:

```
PHP Notice:  Undefined index: SERVER_NAME in /vagrant/www/wc-admin/public_html/wp-includes/pluggable.php on line 330
Notice: Undefined index: SERVER_NAME in /vagrant/www/wc-admin/public_html/wp-includes/pluggable.php on line 330
```

The customers are created fine.

**Comment by kloon** [comment]
This is related to the sending of emails, since WP-CLI is run from command line it does not have the standard server variables set. When WordPress sends emails it uses SERVER_NAME to fill out sender details for the email.

We do have plans to make the email sending disabled by default and then have a flag enable it should you wish, might be good to also add a fix for this then since we will continue to support email sending functionality.

**Comment by rrennick** [comment]
I tested this and didn't get any notices. This was addressed in WP in https://core.trac.wordpress.org/ticket/44569.
